### ISSUE TITLE
Parsing values with YAML bar operator fails.

### ISSUE THREAD

**Issue by SiegfredRodriguez** [rapidsai/frigate#27]
When generating document for fields with bar operator (|), frigate fails:

Sample:

```yaml
myField: | # cant document this
```

Error:

```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/frigate", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/frigate/cli.py", line 25, in gen
    click.echo(frigate.gen.gen(filename, output_format, credits=no_credits))
  File "/usr/local/lib/python3.8/site-packages/frigate/gen.py", line 161, in gen
    return template.render(**chart, values=traverse(values), credits=credits)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/frigate/templates/markdown.jinja2", line 1, in top-level template code
    {% extends "base.jinja2" %}
  File "/usr/local/lib/python3.8/site-packages/frigate/templates/base.jinja2", line 4, in top-level template code
    {% block table %}{% endblock %}
  File "/usr/local/lib/python3.8/site-packages/frigate/templates/markdown.jinja2", line 21, in block "table"
    {% for (param, comment, default) in values -%}
  File "/usr/local/lib/python3.8/site-packages/frigate/gen.py", line 122, in traverse
    for value in traverse(default, root=newroot):
  File "/usr/local/lib/python3.8/site-packages/frigate/gen.py", line 134, in traverse
    comment = get_comment(tree, key)
  File "/usr/local/lib/python3.8/site-packages/frigate/gen.py", line 63, in get_comment
    if comment is not None and comment.start_mark.line == linecol[0]:
AttributeError: 'str' object has no attribute 'start_mark'
```

**Comment by jacobtomlinson** [comment]
Thanks for catching this @SiegfredRodriguez.
